#!/usr/bin/env python3
"""Kernel-factor coordinate and classical reference searches.

The LFK-style routine follows the algebra in Li/Fang/Kuo/Lin (2025) but the
factor-pair table is generated by :mod:`core`; no published lookup table is
copied. The implementation is kept deliberately transparent so operation counts
can be compared against ordinary trial division and a conventional wheel-210
baseline.
"""
from __future__ import annotations

import math
import time
from dataclasses import dataclass, asdict

try:
    from .core import (
        BASE_PRIMES,
        MODULUS,
        ROOTS,
        candidate_factor_pairs,
        is_ptp_candidate,
        ptp_coordinate,
        root_for_integer,
        small_base_factor,
    )
except ImportError:  # direct script execution
    from core import (  # type: ignore
        BASE_PRIMES,
        MODULUS,
        ROOTS,
        candidate_factor_pairs,
        is_ptp_candidate,
        ptp_coordinate,
        root_for_integer,
        small_base_factor,
    )


@dataclass
class SearchStats:
    method: str
    n: int
    factors: tuple[int, int] | None
    candidate_pairs: int = 0
    pair_checks: int = 0
    integer_search_steps: int = 0
    divisibility_tests: int = 0
    elapsed_seconds: float = 0.0

    def to_dict(self) -> dict:
        row = asdict(self)
        row["factors"] = None if self.factors is None else list(self.factors)
        return row


def _ordered_factors(a: int, b: int) -> tuple[int, int]:
    return (a, b) if a <= b else (b, a)


def kernel_coordinate(factor: int) -> tuple[int, int]:
    """Represent factor = q + 210*x and return (q,x)."""
    return ptp_coordinate(factor)


def kernel_equation(
    target_n: int,
    qj: int,
    qk: int,
    theta: int,
    theta_hat: int,
) -> tuple[int, int, bool]:
    """Return (sigma, rhs, equality) for the kernel-factor equation.

    sigma = (N-qj*qk)/210
    rhs   = qj*theta_hat + qk*theta + 210*theta*theta_hat
    """
    delta = int(target_n) - int(qj) * int(qk)
    if delta % MODULUS:
        raise ValueError("qj*qk is not compatible with N modulo 210")
    sigma = delta // MODULUS
    rhs = qj * theta_hat + qk * theta + MODULUS * theta * theta_hat
    return sigma, rhs, sigma == rhs


def _ceil_sqrt_over_210(n: int) -> int:
    s = math.isqrt(n)
    if s * s < n:
        s += 1
    return (s + MODULUS - 1) // MODULUS


def lfk_factor(n: int) -> SearchStats:
    """Factor a semiprime using the generated kernel-factor-pair table.

    This is a classical reference implementation for benchmarking, not a claim
    of asymptotic improvement. For factors 2,3,5,7, it exits through the same
    explicit precheck used by the papers.
    """
    n = int(n)
    t0 = time.perf_counter()
    if n < 4:
        raise ValueError("n must be composite and >= 4")

    small = small_base_factor(n)
    if small is not None:
        other = n // small
        return SearchStats(
            method="lfk210",
            n=n,
            factors=_ordered_factors(small, other),
            divisibility_tests=BASE_PRIMES.index(small) + 1,
            elapsed_seconds=time.perf_counter() - t0,
        )

    if not is_ptp_candidate(n):
        return SearchStats(method="lfk210", n=n, factors=None, elapsed_seconds=time.perf_counter() - t0)

    pairs = candidate_factor_pairs(n)
    bound = _ceil_sqrt_over_210(n)
    pair_checks = 0
    steps = 0
    divisions = len(BASE_PRIMES)

    for qj, qk in pairs:
        pair_checks += 1
        delta = n - qj * qk
        if delta % MODULUS:
            continue
        sigma = delta // MODULUS

        # Paper Eq. (7): theta from a selected theta_hat, theta >= theta_hat.
        for theta_hat in range(bound + 1):
            steps += 1
            numerator = sigma - qj * theta_hat
            denominator = qk + MODULUS * theta_hat
            divisions += 1
            if numerator < 0:
                continue
            theta, rem = divmod(numerator, denominator)
            if rem == 0 and theta >= theta_hat:
                p = qj + MODULUS * theta
                q = qk + MODULUS * theta_hat
                if p > 1 and q > 1 and p * q == n:
                    return SearchStats(
                        "lfk210", n, _ordered_factors(p, q), len(pairs), pair_checks,
                        steps, divisions, time.perf_counter() - t0
                    )

        # Reversed ordering: theta_hat > theta.
        for theta in range(bound + 1):
            steps += 1
            numerator = sigma - qk * theta
            denominator = qj + MODULUS * theta
            divisions += 1
            if numerator < 0:
                continue
            theta_hat, rem = divmod(numerator, denominator)
            if rem == 0 and theta_hat > theta:
                p = qj + MODULUS * theta
                q = qk + MODULUS * theta_hat
                if p > 1 and q > 1 and p * q == n:
                    return SearchStats(
                        "lfk210", n, _ordered_factors(p, q), len(pairs), pair_checks,
                        steps, divisions, time.perf_counter() - t0
                    )

    return SearchStats(
        "lfk210", n, None, len(pairs), pair_checks, steps, divisions,
        time.perf_counter() - t0
    )


def trial_division_factor(n: int) -> SearchStats:
    """Plain integer trial division baseline."""
    n = int(n)
    t0 = time.perf_counter()
    tests = 0
    for d in range(2, math.isqrt(n) + 1):
        tests += 1
        if n % d == 0:
            return SearchStats(
                "trial_division", n, _ordered_factors(d, n // d),
                divisibility_tests=tests, elapsed_seconds=time.perf_counter() - t0
            )
    return SearchStats(
        "trial_division", n, None, divisibility_tests=tests,
        elapsed_seconds=time.perf_counter() - t0
    )


def wheel210_factor(n: int) -> SearchStats:
    """Conventional wheel-210 trial division baseline.

    This is intentionally included because modulo-210 PTP pruning overlaps with
    ordinary wheel-factorization mathematics. Any claimed PTP benefit must beat
    this baseline, not merely plain trial division.
    """
    n = int(n)
    t0 = time.perf_counter()
    tests = 0
    for p in BASE_PRIMES:
        tests += 1
        if n % p == 0:
            return SearchStats(
                "wheel210", n, _ordered_factors(p, n // p),
                divisibility_tests=tests, elapsed_seconds=time.perf_counter() - t0
            )

    limit = math.isqrt(n)
    residues = tuple(r for r in range(1, MODULUS) if math.gcd(r, MODULUS) == 1)
    block = 0
    while block <= limit:
        for residue in residues:
            d = block + residue
            if d < 11:
                continue
            if d > limit:
                return SearchStats(
                    "wheel210", n, None, divisibility_tests=tests,
                    elapsed_seconds=time.perf_counter() - t0
                )
            tests += 1
            if n % d == 0:
                return SearchStats(
                    "wheel210", n, _ordered_factors(d, n // d),
                    divisibility_tests=tests, elapsed_seconds=time.perf_counter() - t0
                )
        block += MODULUS

    return SearchStats(
        "wheel210", n, None, divisibility_tests=tests,
        elapsed_seconds=time.perf_counter() - t0
    )


def verify_actual_pair_present(p: int, q: int) -> bool:
    """Check that the actual factor-root pair occurs in the generated row."""
    n = p * q
    if small_base_factor(n) is not None:
        return True
    rp = root_for_integer(p)
    rq = root_for_integer(q)
    actual = _ordered_factors(rp, rq)
    return actual in candidate_factor_pairs(n)
