#!/usr/bin/env python3
"""Composite-symmetry reproduction and factor-search falsification audit.

The 2026 composite-symmetry paper describes vertical/horizontal/diagonal
mirrors generated by q -> 210-q and h -> 210-h. Here we reproduce those
residue transforms independently and ask the narrower computational question:
can they safely canonicalize the kernel factor-pair search for one fixed N?

Important: modular symmetry does not automatically imply equality of the
integer factor candidates for a fixed semiprime. Reduction is disabled unless
an exhaustive audit proves zero false rejections over the requested range.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, asdict

try:
    from .core import MODULUS, ROOTS, factor_pair_table, root_for_integer, root_for_residue
except ImportError:
    from core import MODULUS, ROOTS, factor_pair_table, root_for_integer, root_for_residue  # type: ignore


def mirror_root(q: int) -> int:
    """Canonical PTP root representing -q (mod 210)."""
    return root_for_residue(-int(q))


def normalize_pair(pair: tuple[int, int]) -> tuple[int, int]:
    a, b = pair
    return (a, b) if a <= b else (b, a)


def vertical_pair(pair: tuple[int, int]) -> tuple[int, int]:
    """Hold first root, mirror the second."""
    a, b = pair
    return normalize_pair((a, mirror_root(b)))


def horizontal_pair(pair: tuple[int, int]) -> tuple[int, int]:
    """Mirror first root, hold the second."""
    a, b = pair
    return normalize_pair((mirror_root(a), b))


def diagonal_pair(pair: tuple[int, int]) -> tuple[int, int]:
    """Mirror both roots; this preserves the target product residue."""
    a, b = pair
    return normalize_pair((mirror_root(a), mirror_root(b)))


def symmetry_orbit(pair: tuple[int, int]) -> tuple[tuple[int, int], ...]:
    p = normalize_pair(pair)
    return tuple(sorted({p, vertical_pair(p), horizontal_pair(p), diagonal_pair(p)}))


def target_root_for_pair(pair: tuple[int, int]) -> int:
    return root_for_residue(pair[0] * pair[1])


def table_symmetry_report() -> dict:
    """Report raw vs diagonal-modular canonical counts by target root.

    The diagonal map preserves the target residue. This report measures only a
    residue-table equivalence. It does NOT authorize dropping mirrored pairs
    from factorization of a fixed integer.
    """
    table = factor_pair_table()
    rows = []
    for target, pairs in table.items():
        canonical = {min(normalize_pair(p), diagonal_pair(p)) for p in pairs}
        closed = all(diagonal_pair(p) in pairs for p in pairs)
        rows.append({
            "target_root": target,
            "raw_candidate_count": len(pairs),
            "diagonal_residue_classes": len(canonical),
            "residue_reduction_factor": len(pairs) / len(canonical),
            "closed_under_diagonal_mirror": closed,
        })
    return {
        "modulus": MODULUS,
        "rows": rows,
        "all_rows_closed": all(r["closed_under_diagonal_mirror"] for r in rows),
    }


def _is_prime(n: int) -> bool:
    if n < 2:
        return False
    if n % 2 == 0:
        return n == 2
    d = 3
    while d * d <= n:
        if n % d == 0:
            return False
        d += 2
    return True


@dataclass
class SymmetryReductionAudit:
    prime_limit: int
    semiprimes_checked: int
    false_rejections: int
    first_counterexample: dict | None
    safe_for_fixed_n_factor_search: bool

    def to_dict(self) -> dict:
        return asdict(self)


def audit_diagonal_canonicalization(prime_limit: int = 2_000) -> SymmetryReductionAudit:
    """Try to falsify diagonal-pair canonicalization for fixed-N factoring.

    Proposed reduction: retain only lexicographically smaller of a root pair and
    its diagonal mirror. If an actual semiprime's factor-root pair is discarded,
    the reduction is unsafe. The audit stops at the first counterexample.
    """
    primes = [
        p for p in range(11, int(prime_limit) + 1)
        if _is_prime(p) and math.gcd(p, MODULUS) == 1
    ]
    checked = 0
    for i, p in enumerate(primes):
        for q in primes[i:]:
            checked += 1
            actual = normalize_pair((root_for_integer(p), root_for_integer(q)))
            canonical = min(actual, diagonal_pair(actual))
            if canonical != actual:
                return SymmetryReductionAudit(
                    prime_limit=prime_limit,
                    semiprimes_checked=checked,
                    false_rejections=1,
                    first_counterexample={
                        "p": p,
                        "q": q,
                        "N": p * q,
                        "actual_root_pair": list(actual),
                        "kept_canonical_pair": list(canonical),
                        "actual_pair_would_be_dropped": True,
                    },
                    safe_for_fixed_n_factor_search=False,
                )
    return SymmetryReductionAudit(prime_limit, checked, 0, None, True)


def full_symmetry_report(prime_limit: int = 2_000) -> dict:
    table = table_symmetry_report()
    audit = audit_diagonal_canonicalization(prime_limit)
    return {
        "table_symmetry": table,
        "factor_search_audit": audit.to_dict(),
        "policy": (
            "Use mirror symmetry for descriptive/table generation only unless a fixed-N "
            "factor-search reduction passes exhaustive no-false-rejection tests."
        ),
    }


if __name__ == "__main__":
    import json

    print(json.dumps(full_symmetry_report(), indent=2, sort_keys=True))
